FROM public.ecr.aws/docker/library/golang:1.26.2

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
RUN GOBIN=/usr/local/bin go install github.com/air-verse/air@v1.65.1

COPY . .

RUN go build -o ./tmp/server ./cmd/server

EXPOSE 8080

CMD ["sh", "-c", "go run ./cmd/migrate up && air"]

