// Code generated from docs/releases and docs/plan; DO NOT EDIT.

package releaseinfo

var releases = []Document{
	{Version: "0.3.2", Date: "2026-08-16", Summary: "Keep curriculum browsing and proposal editing responsive as the curriculum and\nthe number of concurrent contributors grow.", Content: "# 0.3.2\n\n## Main objective\n\nKeep curriculum browsing and proposal editing responsive as the curriculum and\nthe number of concurrent contributors grow.\n\n## Changes\n\n- Separated lightweight curriculum structure reads from full unit content and\n  loaded Markdown only when a unit document is opened.\n- Made curriculum searches return bounded summaries from PostgreSQL instead of\n  materializing every unit's content in application memory.\n- Replaced the global curriculum advisory lock with shared projection locks and\n  proposal-specific row locks, allowing different drafts to change concurrently.\n- Kept rebase planning non-blocking and propagated request cancellation through\n  its read-only database snapshot.\n- Avoided graph reconstruction when a draft already targets the current\n  curriculum proposal.\n- Made curriculum modification content and historical diffs load one focused\n  unit at a time, including proposal-created and retired units.\n- Replaced eager dependency and recognition picker catalogs with debounced,\n  bounded server-side searches that preserve proposal working-state semantics.\n- Made acceptance apply only the accepted proposal to the materialized\n  curriculum instead of replaying the complete publication history.\n- Deferred stale-draft rebases until a draft is opened or modified and avoided\n  calculating full rebase plans for every draft in proposal lists.\n- Resolved MCP proposal-unit responses from focused unit history and immediate\n  relationships instead of reconstructing the complete curriculum graph.\n- Added trigram indexes for published unit name and content search.\n- Bounded expensive graph-order optimization for large proposal overviews.\n- Bounded the PostgreSQL connection pool and exposed its utilization through\n  health response headers."},
	{Version: "0.3.1", Date: "2026-08-15", Summary: "Help curriculum contributors and agents produce complete, reusable learning\nunits with coherent prerequisite boundaries.", Content: "# 0.3.1\n\n## Main objective\n\nHelp curriculum contributors and agents produce complete, reusable learning\nunits with coherent prerequisite boundaries.\n\n## Changes\n\n- Established a canonical editorial contract for learner-facing unit content,\n  including sufficient intuition, formalism and worked examples where needed.\n- Clarified how to factor shared knowledge into focused units without\n  duplication, partial overlap or hidden prerequisites.\n- Exposed the same canonical authoring documents through MCP resources and the\n  argument-free `get_authoring_guidance` tool, so agents can load them even\n  when their host does not provide resource reads.\n- Directed MCP agents to load that guidance before authoring, search for\n  existing knowledge and preserve the same expectations in unit creation,\n  editing and dependency tools."},
	{Version: "0.3.0", Date: "2026-08-14", Summary: "Open curriculum development to selected contributors while keeping proposal\nacceptance subject to manual administrator approval.", Content: "# 0.3.0\n\n## Main objective\n\nOpen curriculum development to selected contributors while keeping proposal\nacceptance subject to manual administrator approval.\n\n## Features\n\n- Added contributor access managed through single-use, expiring administrator\n  invitations, while public registration continues to create regular members.\n- Added user administration with contributor status, active invitations and\n  each user's proposal history.\n- Allowed contributors to create private drafts and submit immutable active\n  proposals for shared review.\n- Added administrator acceptance and rejection without deleting rejected work,\n  preserving it as a reference for its authors and administrators.\n- Reused the curriculum modification workspace for read-only proposal review,\n  including proposal and unit diffs, with administrator decision actions.\n- Exposed the contributor submission and administrator decision workflow\n  consistently through web, REST and MCP."},
	{Version: "0.2.8", Date: "2026-08-14", Summary: "Strengthen curriculum workflows and keep their behaviour consistent across\nweb, REST and MCP.", Content: "# 0.2.8\n\n## Main objective\n\nStrengthen curriculum workflows and keep their behaviour consistent across\nweb, REST and MCP.\n\n## Changes\n\n- Preserved learning-path targets across curriculum publications by migrating\n  them through recognitions.\n- Improved proposal history by placing draft branches above the proposal state\n  they build on.\n- Made curriculum behaviour more consistent across web, REST and MCP while\n  simplifying the shared workflows behind them."},
	{Version: "0.2.7", Date: "2026-08-09", Summary: "Refine proposal history navigation and make project evolution visible.", Content: "# 0.2.7\n\n## Main objective\n\nRefine proposal history navigation and make project evolution visible.\n\n## Changes\n\n- Clarified incremental proposal history with a continuation fade and removed\n  redundant arrows from proposal links.\n- Rebalanced historical proposal panes so the active unit content receives\n  priority while the history remains compact context.\n- Added Releases and Roadmap to About, backed by the canonical release and plan\n  documents and sharing the same list-and-detail infrastructure as\n  Documentation.\n- Exposed the current application version consistently across About, REST and\n  MCP."},
	{Version: "0.2.6", Date: "2026-08-09", Summary: "Improve historical proposal inspection.", Content: "# 0.2.6\n\n## Main objective\n\nImprove historical proposal inspection.\n\n## Changes\n\n- Corrected historical arrows to point from older states to newer ones and\n  clarified incremental loading with a faded continuation.\n- Added a read-only graph to accepted proposal details, including unit\n  navigation, dependency context and content inspection at that curriculum\n  state."},
	{Version: "0.2.5", Date: "2026-08-09", Summary: "Make proposal review and pane navigation more predictable.", Content: "# 0.2.5\n\n## Main objective\n\nMake proposal review and pane navigation more predictable.\n\n## Changes\n\n- Made pane breadcrumbs converge on canonical server-rendered state, preserved\n  proposal navigation position and constrained long breadcrumb labels.\n- Made published proposal details accessible from history, ordered history and\n  rebase timelines newest-first, and added incremental history loading.\n- Made content diffs treat rewritten paragraphs as complete replacements while\n  retaining word-level detail for small edits.\n- Clarified the draft list and the distinction between publishing and accepting\n  a proposal, with small visual refinements to proposal changes."},
	{Version: "0.2.4", Date: "2026-08-08", Summary: "Make graph navigation and unit content controls clearer in narrow layouts.", Content: "# 0.2.4\n\n## Main objective\n\nMake graph navigation and unit content controls clearer in narrow layouts.\n\n## Changes\n\n- Restored ordinary graph and search navigation after closing a unit's content\n  reader, while retaining quick content switching while the reader is open.\n- Aligned the unit completion action naturally below narrow titles and removed\n  unnecessary button padding.\n- Reduced graph title weight and line height, with slightly smaller text,\n  spacing and nodes when the graph's own container is narrow."},
	{Version: "0.2.3", Date: "2026-08-08", Summary: "Improve multi-pane layout consistency and reduce production runtime overhead.", Content: "# 0.2.3\n\n## Main objective\n\nImprove multi-pane layout consistency and reduce production runtime overhead.\n\n## Changes\n\n- Coordinated horizontal padding across visible content panes while preserving\n  fixed navigation and structural pane widths.\n- Treated declared content modes as usable inner widths and aligned bounded\n  lists and forms with their actual readable measures.\n- Allocated surplus proposal workspace width to the dense proposal view instead\n  of the bounded unit reader.\n- Kept narrow unit titles readable by moving completion actions onto their own\n  row when necessary.\n- Replaced aggregate proposal change totals with compact counts by change type.\n- Reused immutable normal and administrator MCP server instances while keeping\n  authentication and user identity request-scoped.\n- Set Render's Go runtime memory limit to 400 MiB."},
	{Version: "0.2.2", Date: "2026-08-08", Summary: "Make curriculum guidance available to people and agents while improving the\nresponsiveness of large proposal graphs.", Content: "# 0.2.2\n\n## Main objective\n\nMake curriculum guidance available to people and agents while improving the\nresponsiveness of large proposal graphs.\n\n## Changes\n\n- Added concise About documentation backed by one canonical Markdown source\n  shared with MCP resources.\n- Made Markdown, LaTeX and final-state proposal semantics directly discoverable\n  from the relevant MCP tools.\n- Improved Documentation panel layout and navigation continuity.\n- Reduced curriculum layout search from 512 to 128 candidates.\n- Reused SVG path samples and skipped geometrically impossible collision checks\n  without changing graph routing criteria.\n- Reorganized implementation packages under the four top-level backend layers."},
	{Version: "0.2.1", Date: "2026-08-08", Summary: "Make draft proposals represent their final proposed state rather than the\nediting history of units created within the same draft.", Content: "# 0.2.1\n\n## Main objective\n\nMake draft proposals represent their final proposed state rather than the\nediting history of units created within the same draft.\n\n## Changes\n\n- Updating a unit created by the same proposal now updates its existing\n  `create_unit` change while preserving the unit identity.\n- Repeated REST API, MCP and web edits converge to one creation containing the\n  final name and content.\n- Updates to published units continue to use explicit rename and content\n  changes."},
	{Version: "0.2.0", Date: "2026-08-08", Summary: "Provide experimental REST and MCP interfaces for agent clients to interact with\nevery platform capability delivered in 0.1.0.", Content: "# 0.2.0\n\n## Main objective\n\nProvide experimental REST and MCP interfaces for agent clients to interact with\nevery platform capability delivered in 0.1.0.\n\n## Features\n\n- An OpenAPI contract for an experimental, unversioned `/api` surface. The API\n  may change between 0.x releases; a stable versioned path is deferred until\n  the compatibility policy is known.\n- Consistent JSON resources, errors, strict request validation and pagination\n  for growing collections.\n- Personal bearer tokens that inherit their owner's permissions, are shown\n  once, and are stored only as cryptographic hashes.\n- Public reads for the current published curriculum, units, dependencies and\n  accepted proposal history.\n- Private learning-path and recommendation operations, plus progress reporting\n  with `direct`, `recognized` and `completed` states.\n- Administrator proposal editing, conflict resolution and publication through\n  the same services used by the web interface.\n- An agent-oriented MCP server with resources, structured tools and guidance\n  for curriculum discovery, learning workflows and administrator proposals.\n- OAuth 2.1 authorization-code support with PKCE and Client ID Metadata\n  Documents, allowing remote agent clients to connect to a user's account and\n  users to inspect or revoke those connections alongside personal API tokens."},
	{Version: "0.1.0", Date: "2026-08-06", Summary: "Deliver the first usable release, with public curriculum access and curriculum\nmodification restricted to an administrator account.", Content: "# 0.1.0\n\n## Main objective\n\nDeliver the first usable release, with public curriculum access and curriculum\nmodification restricted to an administrator account.\n\n## Features\n\n- Proposal-based curriculum modification for administrators, covering units,\n  dependencies, content and recognitions while preserving durable identities\n  and history.\n- Immediate acceptance of administrator-published proposals.\n- Public graph browsing, search, navigation and unit content access.\n- Account registration, sign-in and recovery.\n- Personal learning paths and unit completion tracking."},
}

var roadmap = []Document{
	{Version: "0.4.0", Summary: "Extend the invitation system so contributors can invite other contributors to\nthe platform.", Content: "# 0.4.0\n\n## Main objective\n\nExtend the invitation system so contributors can invite other contributors to\nthe platform.\n\n## TODOs\n\n- Allow contributors to invite other contributors to the platform.\n- Provide controls for enabling or disabling contributor invitations and\n  configuring their renewal interval."},
	{Version: "0.5.0", Summary: "Add asset support to the platform.", Content: "# 0.5.0\n\n## Main objective\n\nAdd asset support to the platform."},
	{Version: "0.6.0", Summary: "Introduce a feedback system.", Content: "# 0.6.0\n\n## Main objective\n\nIntroduce a feedback system."},
	{Version: "0.7.0", Summary: "Introduce embeddings.", Content: "# 0.7.0\n\n## Main objective\n\nIntroduce embeddings."},
	{Version: "0.8.0", Summary: "Introduce polling for proposals while still requiring manual administrator\napproval.", Content: "# 0.8.0\n\n## Main objective\n\nIntroduce polling for proposals while still requiring manual administrator\napproval."},
	{Version: "0.9.0", Summary: "Make poll results determine whether a proposal is accepted.", Content: "# 0.9.0\n\n## Main objective\n\nMake poll results determine whether a proposal is accepted."},
	{Version: "0.10.0", Summary: "Open curriculum development to all users.", Content: "# 0.10.0\n\n## Main objective\n\nOpen curriculum development to all users."},
	{Version: "1.0.0", Summary: "Establish a stable standard.", Content: "# 1.0.0\n\n## Main objective\n\nEstablish a stable standard."},
}
